spring:
  application:
    name: meli-challenge
  profiles:
    active: local
  cache:
    infinispan:
      config: classpath:config.xml
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        webclient-get: true
        client-get: true
        http-get: true
        webapi-client: true
        cache: true
        cache-find: true
        filter-handler: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


resilience4j:
  retry:
    instances:
      getAPIRetry:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      legacy:
        enabled: true
      enabled: true

infinispan:
  embedded:
    enabled: true


routes:
  server: "https://api.mercadolibre.com"